MERGE INTO AGE_ADJUSTMENT_RATE SELECT * FROM CSVREAD('classpath:/data/AGE_ADJUSTMENT_RATE.csv');
MERGE INTO INSURANCE_TYPE SELECT * FROM CSVREAD('classpath:/data/INSURANCE_TYPE.csv');
MERGE INTO JOB_TYPE SELECT * FROM CSVREAD('classpath:/data/JOB_TYPE.csv');
MERGE INTO MARRIED_TYPE SELECT * FROM CSVREAD('classpath:/data/MARRIED_TYPE.csv');
MERGE INTO TREATED_TYPE SELECT * FROM CSVREAD('classpath:/data/TREATED_TYPE.csv');
